import { Bebas_Neue } from "next/font/google";
import "./globals.css";
import { Footer } from "./reusable-components/Footer";
import { Navbar } from "./reusable-components/Navbar";

const bebas = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "DES X",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bebas.variable} antialiased cursor-default`}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
